/**
 * featureStubRoutes.ts
 * ════════════════════
 * Graceful stub endpoints for features that are planned but not yet built.
 * Returns 503 with { available: false, message, feature } so client pages
 * can degrade cleanly instead of throwing unhandled 404 errors.
 *
 * Each stub fires a Trinity event so usage patterns are tracked and 
 * prioritized for implementation.
 *
 * Generated by Phase 6 audit — 2026-05-01
 */

import { Router } from 'express';
import { requireAuth } from '../auth';
import { ensureWorkspaceAccess } from '../middleware/workspaceScope';
import type { AuthenticatedRequest } from '../rbac';
import { createLogger } from '../lib/logger';

const log = createLogger('FeatureStubs');
const router = Router();

function stub(feature: string, eta?: string) {
  return async (req: AuthenticatedRequest, res: any) => {
    log.info(`[FeatureStub] ${feature} accessed by workspace ${req.workspaceId || 'unknown'}`);
    // Non-blocking Trinity notification so feature demand is tracked
    Promise.resolve().then(async () => {
      try {
        const { platformEventBus } = await import('../services/platformEventBus');
        platformEventBus.publish({
          type: 'feature_accessed_stub',
          workspaceId: req.workspaceId || 'platform',
          metadata: { feature, path: req.path, method: req.method },
        }).catch(() => null);
      } catch (_) { /* non-blocking */ }
    });
    return res.status(503).json({
      available: false,
      feature,
      message: eta
        ? `${feature} is coming soon (ETA: ${eta}). We\'ve noted your interest.`
        : `${feature} is not yet available in this workspace tier.`,
    });
  };
}

// ── Budgeting ──────────────────────────────────────────────────────────────────
router.get('/budgets',    requireAuth, ensureWorkspaceAccess, stub('Budgeting', 'Q3 2026'));
router.post('/budgets',   requireAuth, ensureWorkspaceAccess, stub('Budgeting', 'Q3 2026'));

// ── CAD (Computer-Aided Dispatch) ──────────────────────────────────────────────
router.get('/cad',        requireAuth, ensureWorkspaceAccess, stub('CAD Console', 'Q3 2026'));
router.post('/cad',       requireAuth, ensureWorkspaceAccess, stub('CAD Console', 'Q3 2026'));
router.get('/cad/calls',  requireAuth, ensureWorkspaceAccess, stub('CAD Console', 'Q3 2026'));
router.post('/cad/calls', requireAuth, ensureWorkspaceAccess, stub('CAD Console', 'Q3 2026'));

// ── Bid Analytics ─────────────────────────────────────────────────────────────
router.get('/bid-analytics',       requireAuth, ensureWorkspaceAccess, stub('Bid Analytics'));
router.post('/bid-analytics',      requireAuth, ensureWorkspaceAccess, stub('Bid Analytics'));
router.get('/bid-analytics/:id',   requireAuth, ensureWorkspaceAccess, stub('Bid Analytics'));

// ── Billing — Invoice Preview & Subscription Changes ─────────────────────────
router.get('/billing/invoice-preview',      requireAuth, ensureWorkspaceAccess, stub('Invoice Preview'));
router.post('/billing/invoice-preview',     requireAuth, ensureWorkspaceAccess, stub('Invoice Preview'));
router.post('/billing/subscription/change', requireAuth, ensureWorkspaceAccess, stub('Subscription Management'));

// ── Automation Events ─────────────────────────────────────────────────────────
router.get('/automation-events',      requireAuth, ensureWorkspaceAccess, stub('Automation Event Log'));
router.get('/automation-events/jobs', requireAuth, ensureWorkspaceAccess, stub('Automation Job Queue'));
router.post('/automation/invoice/anchor-close', requireAuth, ensureWorkspaceAccess, stub('Invoice Anchor Automation'));

// ── Audit Suite ───────────────────────────────────────────────────────────────
router.get('/audit-suite/audits',              requireAuth, ensureWorkspaceAccess, stub('Audit Suite'));
router.post('/audit-suite/audits',             requireAuth, ensureWorkspaceAccess, stub('Audit Suite'));
router.get('/audit-suite/citations',           requireAuth, ensureWorkspaceAccess, stub('Citation Management'));
router.get('/audit-suite/visual-compliance',   requireAuth, ensureWorkspaceAccess, stub('Visual Compliance'));
router.post('/audit-suite/visual-compliance',  requireAuth, ensureWorkspaceAccess, stub('Visual Compliance'));
router.get('/audit-suite/visual-compliance/slots', requireAuth, ensureWorkspaceAccess, stub('Visual Compliance'));

// ── Auditor (external auditor portal) ────────────────────────────────────────
router.get('/auditor/audits',          requireAuth, stub('Auditor Portal'));
router.get('/auditor/me/audits',       requireAuth, stub('Auditor Portal'));
router.get('/auditor/compliance-score',requireAuth, stub('Compliance Score'));
router.get('/auditor/compliance-trend',requireAuth, stub('Compliance Trend'));

// ── Accept Handoff (contractor handoff flow) ──────────────────────────────────
router.get('/accept-handoff',  requireAuth, stub('Contractor Handoff'));
router.post('/accept-handoff', requireAuth, stub('Contractor Handoff'));

// ── Admin: End User Controls & Financial ─────────────────────────────────────
router.get('/admin/end-users/access-config',   requireAuth, stub('Platform Admin: End User Controls'));
router.post('/admin/end-users/toggle-ai-brain',requireAuth, stub('Platform Admin: AI Brain Toggle'));
router.post('/admin/financial/provider-topoff',requireAuth, stub('Platform Admin: Financial Top-off'));

// ── AI Brain extras ───────────────────────────────────────────────────────────
router.post('/ai-brain/diagnostic/run-fast',   requireAuth, stub('AI Diagnostics'));
router.get('/ai-brain/sentiment',              requireAuth, stub('AI Sentiment Analysis'));
router.get('/ai-brain/patterns',               requireAuth, stub('AI Patterns'));
router.post('/ai-brain/predict',               requireAuth, stub('AI Predictions'));

// ── Bridge Channels ───────────────────────────────────────────────────────────
router.post('/bridges/send', requireAuth, ensureWorkspaceAccess, stub('Bridge Channels'));

// ── Armory ────────────────────────────────────────────────────────────────────
router.get('/armory/ammo',  requireAuth, ensureWorkspaceAccess, stub('Armory Compliance'));
router.post('/armory/ammo', requireAuth, ensureWorkspaceAccess, stub('Armory Compliance'));

// ── RMS (Records Management System) ──────────────────────────────────────────
router.get('/rms/trespass',  requireAuth, ensureWorkspaceAccess, stub('RMS Trespass Records'));
router.post('/rms/trespass', requireAuth, ensureWorkspaceAccess, stub('RMS Trespass Records'));

export default router;
