/**
 * INDUSTRY STANDARD REPORT TEMPLATES
 * 
 * Pre-loaded templates for universal adaptability across industries.
 * These templates jumpstart adoption by providing immediate value.
 */

export const INDUSTRY_TEMPLATES = [
  // 1. INCIDENT REPORT (Security/Hospital)
  {
    name: "Incident Report",
    description: "Document workplace incidents, safety violations, or security breaches with photos and witness statements",
    category: "security",
    isSystemTemplate: true,
    requiresPhotos: true,
    minPhotos: 1,
    maxPhotos: 10,
    photoInstructions: "Photos must show the incident scene, any damage, and relevant context. Ensure good lighting and clear visibility.",
    fields: [
      {
        id: "incident_date",
        name: "incidentDate",
        label: "Date & Time of Incident",
        type: "datetime",
        required: true,
        autoPopulate: false,
      },
      {
        id: "location",
        name: "location",
        label: "Incident Location",
        type: "text",
        required: true,
        placeholder: "Building, floor, room number",
      },
      {
        id: "incident_type",
        name: "incidentType",
        label: "Type of Incident",
        type: "select",
        required: true,
        options: ["Injury", "Property Damage", "Security Breach", "Safety Violation", "Near Miss", "Other"],
      },
      {
        id: "severity",
        name: "severity",
        label: "Severity Level",
        type: "select",
        required: true,
        options: ["Low", "Medium", "High", "Critical"],
      },
      {
        id: "description",
        name: "description",
        label: "Detailed Description",
        type: "textarea",
        required: true,
        placeholder: "Describe what happened, who was involved, and the sequence of events",
      },
      {
        id: "witnesses",
        name: "witnesses",
        label: "Witnesses Present",
        type: "textarea",
        required: false,
        placeholder: "Names and contact information of witnesses",
      },
      {
        id: "immediate_action",
        name: "immediateAction",
        label: "Immediate Action Taken",
        type: "textarea",
        required: true,
        placeholder: "What actions were taken immediately after the incident?",
      },
      {
        id: "reporter_signature",
        name: "reporterSignature",
        label: "Reporter Signature",
        type: "signature",
        required: true,
      },
    ],
  },

  // 2. VEHICLE PRE-TRIP INSPECTION (Trucking/Logistics)
  {
    name: "Vehicle Pre-Trip Inspection",
    description: "DOT-compliant pre-trip inspection checklist for commercial vehicles with photo documentation",
    category: "logistics",
    isSystemTemplate: true,
    requiresPhotos: true,
    minPhotos: 2,
    maxPhotos: 15,
    photoInstructions: "Capture photos of vehicle exterior, tires, lights, and any defects found during inspection.",
    fields: [
      {
        id: "vehicle_number",
        name: "vehicleNumber",
        label: "Vehicle/Unit Number",
        type: "text",
        required: true,
      },
      {
        id: "license_plate",
        name: "licensePlate",
        label: "License Plate",
        type: "text",
        required: true,
      },
      {
        id: "odometer",
        name: "odometer",
        label: "Odometer Reading",
        type: "number",
        required: true,
      },
      {
        id: "inspection_date",
        name: "inspectionDate",
        label: "Inspection Date & Time",
        type: "datetime",
        required: true,
        autoPopulate: true,
        dataSource: "currentTimestamp",
      },
      {
        id: "tires_condition",
        name: "tiresCondition",
        label: "Tires - Condition & Pressure",
        type: "select",
        required: true,
        options: ["Pass", "Fail", "Needs Attention"],
      },
      {
        id: "lights_signals",
        name: "lightsSignals",
        label: "Lights & Signals",
        type: "select",
        required: true,
        options: ["Pass", "Fail"],
      },
      {
        id: "brakes",
        name: "brakes",
        label: "Brake System",
        type: "select",
        required: true,
        options: ["Pass", "Fail"],
      },
      {
        id: "fluid_levels",
        name: "fluidLevels",
        label: "Fluid Levels (Oil, Coolant, DEF)",
        type: "select",
        required: true,
        options: ["Pass", "Fail", "Low"],
      },
      {
        id: "mirrors_windows",
        name: "mirrorsWindows",
        label: "Mirrors & Windows",
        type: "select",
        required: true,
        options: ["Pass", "Fail"],
      },
      {
        id: "defects_found",
        name: "defectsFound",
        label: "Defects or Concerns",
        type: "textarea",
        required: false,
        placeholder: "List any defects, damage, or concerns noted during inspection",
      },
      {
        id: "safe_to_operate",
        name: "safeToOperate",
        label: "Vehicle Safe to Operate?",
        type: "checkbox",
        required: true,
      },
      {
        id: "driver_signature",
        name: "driverSignature",
        label: "Driver Signature",
        type: "signature",
        required: true,
      },
    ],
  },

  // 3. DAILY INVENTORY COUNT (Retail)
  {
    name: "Daily Inventory Count",
    description: "Track daily inventory levels, discrepancies, and stock movements for retail operations",
    category: "retail",
    isSystemTemplate: true,
    requiresPhotos: false,
    minPhotos: 0,
    maxPhotos: 5,
    photoInstructions: "Optional: Capture photos of damaged goods or significant discrepancies",
    fields: [
      {
        id: "count_date",
        name: "countDate",
        label: "Count Date",
        type: "date",
        required: true,
        autoPopulate: true,
        dataSource: "currentDate",
      },
      {
        id: "location",
        name: "location",
        label: "Store/Warehouse Location",
        type: "text",
        required: true,
        autoPopulate: true,
        dataSource: "clientLocation",
      },
      {
        id: "department",
        name: "department",
        label: "Department/Category",
        type: "select",
        required: true,
        options: ["Electronics", "Apparel", "Food & Beverage", "Home Goods", "Pharmacy", "Other"],
      },
      {
        id: "opening_count",
        name: "openingCount",
        label: "Opening Inventory Count",
        type: "number",
        required: true,
      },
      {
        id: "received",
        name: "received",
        label: "Units Received Today",
        type: "number",
        required: true,
      },
      {
        id: "sold",
        name: "sold",
        label: "Units Sold Today",
        type: "number",
        required: true,
      },
      {
        id: "damaged_lost",
        name: "damagedLost",
        label: "Damaged/Lost Units",
        type: "number",
        required: false,
      },
      {
        id: "closing_count",
        name: "closingCount",
        label: "Closing Physical Count",
        type: "number",
        required: true,
      },
      {
        id: "discrepancy",
        name: "discrepancy",
        label: "Calculated Discrepancy",
        type: "number",
        required: false,
        helpText: "Auto-calculated: (Opening + Received - Sold - Damaged) - Closing",
      },
      {
        id: "notes",
        name: "notes",
        label: "Notes & Explanations",
        type: "textarea",
        required: false,
        placeholder: "Explain any significant discrepancies or unusual activity",
      },
      {
        id: "counter_signature",
        name: "counterSignature",
        label: "Counter Signature",
        type: "signature",
        required: true,
      },
    ],
  },

  // 4. SAFETY HAZARD REPORT (Drilling/Construction)
  {
    name: "Safety Hazard Report",
    description: "Report workplace hazards, unsafe conditions, or OSHA violations with corrective actions",
    category: "construction",
    isSystemTemplate: true,
    requiresPhotos: true,
    minPhotos: 2,
    maxPhotos: 10,
    photoInstructions: "Photos must clearly show the hazard, its location, and surrounding context. Include close-ups and wide shots.",
    fields: [
      {
        id: "report_date",
        name: "reportDate",
        label: "Report Date & Time",
        type: "datetime",
        required: true,
        autoPopulate: true,
        dataSource: "currentTimestamp",
      },
      {
        id: "site_location",
        name: "siteLocation",
        label: "Job Site Location",
        type: "text",
        required: true,
        autoPopulate: true,
        dataSource: "clientJobSite",
      },
      {
        id: "hazard_type",
        name: "hazardType",
        label: "Type of Hazard",
        type: "select",
        required: true,
        options: ["Fall Hazard", "Electrical", "Chemical Exposure", "Heavy Equipment", "Structural Instability", "Fire Risk", "Other"],
      },
      {
        id: "risk_level",
        name: "riskLevel",
        label: "Risk Level",
        type: "select",
        required: true,
        options: ["Low", "Medium", "High", "Imminent Danger"],
      },
      {
        id: "hazard_description",
        name: "hazardDescription",
        label: "Detailed Hazard Description",
        type: "textarea",
        required: true,
        placeholder: "Describe the hazard, its location, and potential consequences",
      },
      {
        id: "workers_affected",
        name: "workersAffected",
        label: "Number of Workers Affected/Exposed",
        type: "number",
        required: false,
      },
      {
        id: "immediate_action",
        name: "immediateAction",
        label: "Immediate Action Taken",
        type: "textarea",
        required: true,
        placeholder: "What was done immediately to mitigate the hazard?",
      },
      {
        id: "corrective_action",
        name: "correctiveAction",
        label: "Recommended Corrective Action",
        type: "textarea",
        required: true,
        placeholder: "What permanent fix or process change is needed?",
      },
      {
        id: "area_secured",
        name: "areaSecured",
        label: "Area Secured/Barricaded?",
        type: "checkbox",
        required: false,
      },
      {
        id: "reporter_signature",
        name: "reporterSignature",
        label: "Reporter Signature",
        type: "signature",
        required: true,
      },
    ],
  },

  // 5. CLIENT FEEDBACK FORM (General Service)
  {
    name: "Client Feedback Form",
    description: "Collect customer satisfaction feedback, service ratings, and improvement suggestions",
    category: "general_service",
    isSystemTemplate: true,
    requiresPhotos: false,
    minPhotos: 0,
    maxPhotos: 3,
    photoInstructions: "Optional: Include photos of completed work or service delivery",
    fields: [
      {
        id: "feedback_date",
        name: "feedbackDate",
        label: "Feedback Date",
        type: "date",
        required: true,
        autoPopulate: true,
        dataSource: "currentDate",
      },
      {
        id: "client_name",
        name: "clientName",
        label: "Client/Customer Name",
        type: "text",
        required: true,
        autoPopulate: true,
        dataSource: "clientName",
      },
      {
        id: "service_date",
        name: "serviceDate",
        label: "Service Date",
        type: "date",
        required: true,
      },
      {
        id: "service_type",
        name: "serviceType",
        label: "Service Type",
        type: "text",
        required: true,
        placeholder: "e.g., Installation, Repair, Consultation",
      },
      {
        id: "overall_satisfaction",
        name: "overallSatisfaction",
        label: "Overall Satisfaction",
        type: "select",
        required: true,
        options: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very Dissatisfied"],
      },
      {
        id: "quality_rating",
        name: "qualityRating",
        label: "Quality of Work (1-5)",
        type: "select",
        required: true,
        options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"],
      },
      {
        id: "timeliness_rating",
        name: "timelinessRating",
        label: "Timeliness (1-5)",
        type: "select",
        required: true,
        options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"],
      },
      {
        id: "professionalism_rating",
        name: "professionalismRating",
        label: "Professionalism (1-5)",
        type: "select",
        required: true,
        options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"],
      },
      {
        id: "comments",
        name: "comments",
        label: "Additional Comments",
        type: "textarea",
        required: false,
        placeholder: "Share your experience, suggestions, or concerns",
      },
      {
        id: "would_recommend",
        name: "wouldRecommend",
        label: "Would you recommend our services to others?",
        type: "select",
        required: true,
        options: ["Definitely Yes", "Probably Yes", "Not Sure", "Probably No", "Definitely No"],
      },
      {
        id: "client_signature",
        name: "clientSignature",
        label: "Client Signature (Optional)",
        type: "signature",
        required: false,
      },
    ],
  },
];

/**
 * Seed industry templates into a workspace
 */
export async function seedIndustryTemplates(workspaceId: string, createdBy: string) {
  const { storage } = await import("../storage");
  
  const seeded = [];
  
  for (const template of INDUSTRY_TEMPLATES) {
    const created = await storage.createReportTemplate({
      ...template,
      workspaceId,
      createdBy,
      isActive: false, // Owner must activate
    });
    seeded.push(created);
  }
  
  return seeded;
}
