/**
 * PDF Engine — Wave 21C
 * ─────────────────────────────────────────────────────────────────────────────
 * Unified PDF generation service. Three outputs:
 *   1. Use of Force Report  — court-ready, Trinity narrative + RKE citations
 *   2. Daily Activity Report — client-facing, professional format
 *   3. DPS Audit Packet     — full Exhibit A/B/C export for regulatory audits
 *
 * Built on pdfTemplateBase.ts (existing design system: navy, gold, PDFKit).
 * Every generated PDF is logged to generated_documents for legal retention.
 * PDFs stream directly to the HTTP response — no GCS dependency.
 *
 * Doc ID format: <TYPE>-<YYYYMMDD>-<8 hex chars>
 * Footer: doc ID + timestamp + "Generated by CoAIleague" + page N of M
 */

import PDFDocument from 'pdfkit';
import crypto from 'crypto';
import { pool } from '../db';
import { createLogger } from '../lib/logger';
import {
  PDF, PAGE,
  renderPdfHeader, renderPdfFooter,
  hlinePdf, sectionBar, fieldPair, zebraRow, loadTenantLogo,
} from './pdfTemplateBase';

const log = createLogger('PDFEngine');

// ── Doc ID generator ──────────────────────────────────────────────────────────

export function generateDocId(type: string): string {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const hex  = crypto.randomBytes(4).toString('hex').toUpperCase();
  const prefix = {
    uof_report:        'UOF',
    dar:               'DAR',
    dps_audit_packet:  'DPS',
    pay_stub:          'PAY',
    incident_report:   'INC',
  }[type] ?? 'DOC';
  return `${prefix}-${date}-${hex}`;
}

// ── Audit log helper ──────────────────────────────────────────────────────────

async function logGeneratedDoc(params: {
  workspaceId: string;
  documentType: string;
  referenceId?: string;
  docId: string;
  fileSizeBytes?: number;
  pageCount?: number;
  generatedBy?: string;
  generatedByName?: string;
  regulatoryCitations?: string[];
}): Promise<void> {
  try {
    await pool.query(
      `INSERT INTO generated_documents
         (workspace_id, document_type, reference_id, doc_id,
          file_size_bytes, page_count, generated_by, generated_by_name,
          regulatory_citations, status, created_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'generated',NOW())
       ON CONFLICT (doc_id) DO NOTHING`,
      [
        params.workspaceId, params.documentType,
        params.referenceId ?? null, params.docId,
        params.fileSizeBytes ?? null, params.pageCount ?? null,
        params.generatedBy ?? null, params.generatedByName ?? null,
        params.regulatoryCitations ?? [],
      ]
    );
  } catch (err) {
    log.warn('[PDFEngine] Audit log failed (non-fatal):', err instanceof Error ? err.message : String(err));
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// OUTPUT 1 — USE OF FORCE REPORT
// Court-ready. Trinity narrative + Graham v. Connor framework + RKE citations.
// ══════════════════════════════════════════════════════════════════════════════

export async function generateUoFReport(params: {
  workspaceId: string;
  incidentId: string;
  generatedBy?: string;
  generatedByName?: string;
}): Promise<{ buffer: Buffer; docId: string; filename: string }> {
  const { workspaceId, incidentId, generatedBy, generatedByName } = params;
  const docId = generateDocId('uof_report');

  // Load incident + reporter + workspace + RKE context
  const [incResult, wsResult] = await Promise.all([
    pool.query(
      `SELECT i.*,
              e.first_name || ' ' || e.last_name AS reporter_name,
              e.guard_card_number, e.license_type,
              s.start_time AS shift_start, s.end_time AS shift_end,
              si.name AS site_name, si.address AS site_address
       FROM incident_reports i
       LEFT JOIN employees e ON e.id::text = i.reported_by
       LEFT JOIN shifts s ON s.id::text = i.shift_id::text
       LEFT JOIN sites si ON si.id::text = i.site_id::text
       WHERE i.id = $1 AND i.workspace_id = $2 LIMIT 1`,
      [incidentId, workspaceId]
    ),
    pool.query(
      `SELECT company_name, phone, email, address, city, state, zip,
              logo_url, license_number
       FROM workspaces WHERE id = $1 LIMIT 1`,
      [workspaceId]
    ),
  ]);

  const inc = incResult.rows[0];
  const ws  = wsResult.rows[0] ?? {};
  if (!inc) throw new Error(`Incident ${incidentId} not found`);

  // Load RKE UoF citations for this workspace's state
  const stateCode = (ws.state || 'TX').toUpperCase();
  const rkeResult = await pool.query(
    `SELECT title, summary, citation FROM regulatory_knowledge_base
     WHERE state_code = ANY($1::text[])
       AND knowledge_type IN ('case_law','uof_guideline','statute','penal_code')
       AND is_active = TRUE
     ORDER BY state_code DESC, knowledge_type
     LIMIT 8`,
    [[stateCode, 'FEDERAL']]
  );
  const citations = rkeResult.rows;

  // Load legal flags from Trinity
  const legalFlags: Array<{ flag: string; severity: string; recommendation: string }> =
    inc.trinity_legal_flags ?? [];

  // Build PDF
  const logoBuffer = await loadTenantLogo(workspaceId);
  const doc = new PDFDocument({ size: 'LETTER', margin: 0, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));

  const generatedAt = new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' });

  renderPdfHeader(doc, {
    title: 'USE OF FORCE REPORT',
    subtitle: `Incident ${inc.incident_number ?? incidentId.slice(0, 8).toUpperCase()}`,
    workspaceName: ws.company_name ?? 'Security Company',
    tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `Report #: ${inc.incident_number ?? 'N/A'}`,
    generatedLabel: `Generated: ${generatedAt}`,
  });

  doc.font('Helvetica').fontSize(10).fillColor(PDF.dark);
  let y = PAGE.MT;

  // ── Section 1: Incident Overview ─────────────────────────────────────────
  sectionBar(doc, 'SECTION 1 — INCIDENT OVERVIEW');
  y = doc.y + 6;
  fieldPair(doc, 'Incident Number', inc.incident_number ?? 'AUTO-ASSIGNED');
  fieldPair(doc, 'Incident Type', (inc.incident_type ?? '').replace(/_/g, ' ').toUpperCase());
  fieldPair(doc, 'Severity', (inc.severity ?? 'medium').toUpperCase());
  fieldPair(doc, 'Date/Time', inc.created_at ? new Date(inc.created_at).toLocaleString() : 'Unknown');
  fieldPair(doc, 'Location', inc.location_address ?? inc.site_name ?? 'See report');
  fieldPair(doc, 'Site', inc.site_name ?? '—');
  if (inc.gps_latitude && inc.gps_longitude) {
    fieldPair(doc, 'GPS Coordinates', `${Number(inc.gps_latitude).toFixed(6)}, ${Number(inc.gps_longitude).toFixed(6)}`);
  }
  hlinePdf(doc);

  // ── Section 2: Reporting Officer ─────────────────────────────────────────
  sectionBar(doc, 'SECTION 2 — REPORTING OFFICER');
  fieldPair(doc, 'Officer Name', inc.reporter_name ?? generatedByName ?? 'Unknown');
  fieldPair(doc, 'Guard Card / License #', inc.guard_card_number ?? '—');
  fieldPair(doc, 'License Classification',
    inc.license_type
      ? inc.license_type.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())
      : '—'
  );
  if (inc.shift_start) {
    fieldPair(doc, 'Shift Start', new Date(inc.shift_start).toLocaleString());
    fieldPair(doc, 'Shift End', inc.shift_end ? new Date(inc.shift_end).toLocaleString() : 'Ongoing');
  }
  hlinePdf(doc);

  // ── Section 3: Trinity AI Narrative ──────────────────────────────────────
  sectionBar(doc, 'SECTION 3 — INCIDENT NARRATIVE (TRINITY AI ENHANCED)');
  doc.y += 4;
  doc.fillColor(PDF.gray).fontSize(8)
    .text('The following narrative was reviewed and polished by Trinity AI using the Graham v. Connor objective reasonableness framework.', PAGE.ML, doc.y, { width: PAGE.CW })
    .moveDown(0.5);

  if (inc.polished_description) {
    doc.fontSize(10).fillColor(PDF.dark)
      .text(inc.polished_description, PAGE.ML, doc.y, { width: PAGE.CW, lineGap: 2 });
  } else if (inc.raw_description) {
    doc.fontSize(10).fillColor(PDF.dark)
      .text(inc.raw_description, PAGE.ML, doc.y, { width: PAGE.CW, lineGap: 2 });
    doc.fillColor(PDF.warn).fontSize(8)
      .text('[NOTE: This narrative has not yet been reviewed by Trinity AI. Please review before submitting.]', PAGE.ML, doc.y + 4, { width: PAGE.CW });
  }
  doc.moveDown(0.5);

  // Trinity summary box
  if (inc.polished_summary) {
    doc.y += 4;
    doc.rect(PAGE.ML, doc.y, PAGE.CW, 2).fill(PDF.navyMid);
    doc.y += 6;
    doc.fontSize(8).fillColor(PDF.navyMid).font('Helvetica-Bold')
      .text('TRINITY SUMMARY', PAGE.ML, doc.y);
    doc.font('Helvetica').fillColor(PDF.dark).fontSize(9)
      .text(inc.polished_summary, PAGE.ML, doc.y + 12, { width: PAGE.CW });
    doc.moveDown(1);
  }
  hlinePdf(doc);

  // ── Section 4: Graham v. Connor Analysis ────────────────────────────────
  sectionBar(doc, 'SECTION 4 — OBJECTIVE REASONABLENESS ANALYSIS (Graham v. Connor)');
  doc.y += 4;
  const grahamFactors = [
    { label: 'Factor 1 — Severity of Crime', field: '___________________________________________' },
    { label: 'Factor 2 — Immediate Threat to Safety', field: '___________________________________________' },
    { label: 'Factor 3 — Active Resistance / Attempt to Evade', field: '___________________________________________' },
    { label: 'De-escalation Attempted?', field: '___________________________________________' },
    { label: 'Force Type Used', field: '___________________________________________' },
  ];
  grahamFactors.forEach(f => zebraRow(doc, f.label, f.field));
  hlinePdf(doc);

  // ── Section 5: Witnesses ─────────────────────────────────────────────────
  sectionBar(doc, 'SECTION 5 — WITNESSES');
  const witnesses: Array<{ name: string; contact?: string; statement?: string }> =
    inc.witness_statements ?? [];
  if (witnesses.length === 0) {
    doc.fontSize(9).fillColor(PDF.gray).text('No witnesses documented.', PAGE.ML, doc.y + 4, { width: PAGE.CW });
    doc.moveDown(0.5);
  } else {
    witnesses.forEach((w, i) => {
      fieldPair(doc, `Witness ${i + 1}`, `${w.name}${w.contact ? ' — ' + w.contact : ''}`);
      if (w.statement) {
        doc.fontSize(9).fillColor(PDF.grayDark)
          .text(`"${w.statement}"`, PAGE.ML + 16, doc.y, { width: PAGE.CW - 16 });
      }
    });
  }
  hlinePdf(doc);

  // ── Section 6: Legal Flags (Trinity) ────────────────────────────────────
  if (legalFlags.length > 0) {
    sectionBar(doc, 'SECTION 6 — TRINITY LEGAL FLAGS');
    doc.y += 4;
    legalFlags.forEach(flag => {
      const color = flag.severity === 'critical' ? PDF.danger : PDF.warn;
      doc.fontSize(9).fillColor(color).font('Helvetica-Bold')
        .text(`⚠ ${flag.severity.toUpperCase()}: ${flag.flag}`, PAGE.ML, doc.y, { width: PAGE.CW });
      doc.font('Helvetica').fillColor(PDF.dark).fontSize(8)
        .text(flag.recommendation, PAGE.ML + 12, doc.y + 2, { width: PAGE.CW - 12 });
      doc.moveDown(0.4);
    });
    hlinePdf(doc);
  }

  // ── Section 7: Regulatory Citations (RKE) ───────────────────────────────
  if (citations.length > 0) {
    sectionBar(doc, 'SECTION 7 — APPLICABLE LAW & REGULATORY CITATIONS');
    doc.y += 4;
    citations.forEach(cite => {
      doc.fontSize(9).fillColor(PDF.navyMid).font('Helvetica-Bold')
        .text(cite.title, PAGE.ML, doc.y, { width: PAGE.CW });
      if (cite.citation) {
        doc.font('Helvetica-Oblique').fillColor(PDF.gray).fontSize(8)
          .text(cite.citation, PAGE.ML + 8, doc.y + 1, { width: PAGE.CW - 8 });
      }
      doc.font('Helvetica').fillColor(PDF.grayDark).fontSize(8)
        .text(cite.summary.slice(0, 280) + (cite.summary.length > 280 ? '…' : ''), PAGE.ML + 8, doc.y + 2, { width: PAGE.CW - 8 });
      doc.moveDown(0.5);
    });
    hlinePdf(doc);
  }

  // ── Section 8: Signature ─────────────────────────────────────────────────
  sectionBar(doc, 'SECTION 8 — SUPERVISOR REVIEW & SIGNATURE');
  doc.y += 8;
  doc.fontSize(9).fillColor(PDF.dark)
    .text('I certify that the information contained in this report is accurate and complete to the best of my knowledge.', PAGE.ML, doc.y, { width: PAGE.CW });
  doc.y += 20;
  ['Supervisor Signature', 'Print Name', 'Title', 'Date'].forEach(label => {
    doc.fontSize(9).fillColor(PDF.gray).text(label + ':', PAGE.ML, doc.y);
    doc.moveTo(PAGE.ML + 80, doc.y + 2).lineTo(PAGE.ML + PAGE.CW, doc.y + 2)
      .stroke(PDF.grayBorder);
    doc.y += 18;
  });

  renderPdfFooter(doc, {
    docId,
    docType: 'USE OF FORCE REPORT',
    workspaceName: ws.company_name ?? 'Security Company',
  });

  await new Promise<void>(resolve => { doc.end(); doc.on('end', resolve); });
  const buffer = Buffer.concat(chunks);

  await logGeneratedDoc({
    workspaceId, documentType: 'uof_report', referenceId: incidentId,
    docId, fileSizeBytes: buffer.length,
    generatedBy, generatedByName,
    regulatoryCitations: citations.map(c => c.citation).filter(Boolean),
  });

  log.info(`[PDFEngine] UoF Report generated: ${docId} (${Math.round(buffer.length / 1024)}KB)`);
  return { buffer, docId, filename: `UoF-Report-${inc.incident_number ?? incidentId.slice(0,8)}-${docId}.pdf` };
}

// ══════════════════════════════════════════════════════════════════════════════
// OUTPUT 2 — DAILY ACTIVITY REPORT (DAR)
// Client-facing. Professional format. Activity timeline.
// ══════════════════════════════════════════════════════════════════════════════

export async function generateDAR(params: {
  workspaceId: string;
  darId: string;
  generatedBy?: string;
  generatedByName?: string;
}): Promise<{ buffer: Buffer; docId: string; filename: string }> {
  const { workspaceId, darId, generatedBy, generatedByName } = params;
  const docId = generateDocId('dar');

  const [darResult, wsResult] = await Promise.all([
    pool.query(
      `SELECT d.*,
              e.first_name || ' ' || e.last_name AS officer_name,
              e.guard_card_number, e.license_type,
              c.name AS client_name
       FROM daily_activity_reports d
       LEFT JOIN employees e ON e.id = d.employee_id
       LEFT JOIN clients c ON c.id::text = d.client_id
       WHERE d.id = $1 AND d.workspace_id = $2 LIMIT 1`,
      [darId, workspaceId]
    ),
    pool.query(
      `SELECT company_name, phone, email, address, city, state, zip, logo_url
       FROM workspaces WHERE id = $1 LIMIT 1`,
      [workspaceId]
    ),
  ]);

  const dar = darResult.rows[0];
  const ws  = wsResult.rows[0] ?? {};
  if (!dar) throw new Error(`DAR ${darId} not found`);

  const logoBuffer = await loadTenantLogo(workspaceId);
  const doc = new PDFDocument({ size: 'LETTER', margin: 0, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));

  const shiftDate = dar.shift_date ? new Date(dar.shift_date).toLocaleDateString('en-US',
    { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : 'Unknown Date';
  const generatedAt = new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' });

  renderPdfHeader(doc, {
    title: 'DAILY ACTIVITY REPORT',
    subtitle: shiftDate,
    workspaceName: ws.company_name ?? 'Security Company',
    tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `DAR #: ${dar.report_number ?? darId.slice(0, 8).toUpperCase()}`,
    generatedLabel: `Generated: ${generatedAt}`,
  });

  // ── Assignment ────────────────────────────────────────────────────────────
  sectionBar(doc, 'ASSIGNMENT DETAILS');
  fieldPair(doc, 'Client', dar.client_name ?? '—');
  fieldPair(doc, 'Site / Location', dar.site_name ?? '—');
  fieldPair(doc, 'Reporting Officer', dar.officer_name ?? dar.employee_name ?? '—');
  fieldPair(doc, 'License #', dar.guard_card_number ?? '—');
  fieldPair(doc, 'Date', shiftDate);
  fieldPair(doc, 'Shift Start', dar.shift_start ?? '—');
  fieldPair(doc, 'Shift End', dar.shift_end ?? '—');
  if (dar.weather_conditions) fieldPair(doc, 'Weather', dar.weather_conditions);
  hlinePdf(doc);

  // ── Activity Summary ──────────────────────────────────────────────────────
  sectionBar(doc, 'ACTIVITY SUMMARY');
  doc.y += 4;
  doc.fontSize(10).fillColor(PDF.dark)
    .text(dar.activity_summary ?? 'No activity summary provided.', PAGE.ML, doc.y, { width: PAGE.CW, lineGap: 2 });
  doc.moveDown(0.5);
  hlinePdf(doc);

  // ── Statistics ────────────────────────────────────────────────────────────
  sectionBar(doc, 'PATROL STATISTICS');
  if (dar.patrol_count != null) zebraRow(doc, 'Patrol Rounds Completed', String(dar.patrol_count));
  if (dar.vehicle_checks != null) zebraRow(doc, 'Vehicle Checks', String(dar.vehicle_checks));
  zebraRow(doc, 'Incidents Occurred', dar.incidents_occurred ? 'YES — See Attached' : 'None');
  hlinePdf(doc);

  // ── Notes ─────────────────────────────────────────────────────────────────
  if (dar.notes) {
    sectionBar(doc, 'ADDITIONAL NOTES');
    doc.y += 4;
    doc.fontSize(10).fillColor(PDF.dark)
      .text(dar.notes, PAGE.ML, doc.y, { width: PAGE.CW, lineGap: 2 });
    doc.moveDown(0.5);
    hlinePdf(doc);
  }

  // ── Signature ─────────────────────────────────────────────────────────────
  sectionBar(doc, 'OFFICER CERTIFICATION');
  doc.y += 6;
  doc.fontSize(9).fillColor(PDF.dark)
    .text('I certify that all information in this report is accurate.', PAGE.ML, doc.y, { width: PAGE.CW });
  doc.y += 18;
  ['Officer Signature', 'Print Name', 'Date'].forEach(label => {
    doc.fontSize(9).fillColor(PDF.gray).text(label + ':', PAGE.ML, doc.y);
    doc.moveTo(PAGE.ML + 80, doc.y + 2).lineTo(PAGE.ML + 300, doc.y + 2).stroke(PDF.grayBorder);
    doc.y += 18;
  });

  renderPdfFooter(doc, {
    docId, docType: 'DAILY ACTIVITY REPORT', workspaceName: ws.company_name ?? 'Security Company',
  });

  await new Promise<void>(resolve => { doc.end(); doc.on('end', resolve); });
  const buffer = Buffer.concat(chunks);

  await logGeneratedDoc({
    workspaceId, documentType: 'dar', referenceId: darId,
    docId, fileSizeBytes: buffer.length, generatedBy, generatedByName,
  });

  log.info(`[PDFEngine] DAR generated: ${docId} (${Math.round(buffer.length / 1024)}KB)`);
  return { buffer, docId, filename: `DAR-${dar.report_number ?? darId.slice(0,8)}-${docId}.pdf` };
}

// ══════════════════════════════════════════════════════════════════════════════
// OUTPUT 3 — DPS AUDIT PACKET
// Full Exhibit A/B/C. Redacted. Court-ready. Branded.
// ══════════════════════════════════════════════════════════════════════════════

export async function generateDPSAuditPacket(params: {
  workspaceId: string;
  generatedBy?: string;
  generatedByName?: string;
  auditLabel?: string;
}): Promise<{ buffer: Buffer; docId: string; filename: string; pageCount: number }> {
  const { workspaceId, generatedBy, generatedByName, auditLabel } = params;
  const docId = generateDocId('dps_audit_packet');

  // Load all data in parallel
  const [wsResult, officersResult, incidentsResult, shiftsResult, srcResult, preAuditResult] = await Promise.all([
    pool.query(
      `SELECT company_name, phone, email, address, city, state, zip,
              logo_url, license_number
       FROM workspaces WHERE id = $1 LIMIT 1`,
      [workspaceId]
    ),
    // Exhibit A — officers (redacted)
    pool.query(
      `SELECT first_name, last_name, guard_card_number, guard_card_expiry_date,
              guard_card_status, license_type, is_armed, armed_license_verified
       FROM employees
       WHERE workspace_id = $1 AND is_active = TRUE
       ORDER BY last_name, first_name`,
      [workspaceId]
    ),
    // Exhibit B — UoF incidents
    pool.query(
      `SELECT incident_number, title, incident_type, severity, created_at,
              polished_description, status
       FROM incident_reports
       WHERE workspace_id = $1
         AND incident_type IN (
           'use_of_force','firearm_discharge','physical_altercation',
           'use_of_force_incident','weapon_drawn','officer_involved'
         )
       ORDER BY created_at DESC LIMIT 100`,
      [workspaceId]
    ),
    // Exhibit C — armed shift logs
    pool.query(
      `SELECT s.start_time, s.end_time, s.status,
              e.first_name || ' ' || e.last_name AS officer_name,
              e.guard_card_number,
              si.name AS site_name
       FROM shifts s
       LEFT JOIN employees e ON e.id = s.assigned_employee_id
       LEFT JOIN sites si ON si.id = s.site_id
       WHERE s.workspace_id = $1
         AND s.is_armed_post = TRUE
         AND s.start_time >= NOW() - INTERVAL '12 months'
       ORDER BY s.start_time DESC LIMIT 200`,
      [workspaceId]
    ),
    // State regulatory config
    pool.query(
      `SELECT w.state, src.state_name, src.licensing_authority
       FROM workspaces w
       LEFT JOIN state_regulatory_config src ON src.state_code = UPPER(w.state)
       WHERE w.id = $1 LIMIT 1`,
      [workspaceId]
    ),
    // Pre-audit flags (reuse existing scan)
    pool.query(
      `SELECT e.first_name || ' ' || e.last_name AS name,
              e.guard_card_expiry_date, e.guard_card_status, e.license_type,
              e.is_armed
       FROM employees e
       WHERE e.workspace_id = $1 AND e.is_active = TRUE AND e.is_armed = TRUE
         AND (e.guard_card_status = 'expired_hard_block'
              OR e.guard_card_expiry_date < NOW())`,
      [workspaceId]
    ),
  ]);

  const ws        = wsResult.rows[0] ?? {};
  const officers  = officersResult.rows;
  const incidents = incidentsResult.rows;
  const shifts    = shiftsResult.rows;
  const src       = srcResult.rows[0] ?? {};
  const expiredOfficers = preAuditResult.rows;

  const regulatoryBody = src.licensing_authority ?? 'State Regulatory Authority';
  const stateName = src.state_name ?? (src.state ?? 'TX');

  const logoBuffer = await loadTenantLogo(workspaceId);
  const doc = new PDFDocument({ size: 'LETTER', margin: 0, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));

  const generatedAt = new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' });

  // ── Cover Page ────────────────────────────────────────────────────────────
  renderPdfHeader(doc, {
    title: 'REGULATORY COMPLIANCE AUDIT PACKET',
    subtitle: auditLabel ?? `${stateName} Regulatory Audit — ${new Date().getFullYear()}`,
    workspaceName: ws.company_name ?? 'Security Company',
    tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `Packet ID: ${docId}`,
    generatedLabel: `Generated: ${generatedAt}`,
  });

  // Cover info block
  sectionBar(doc, 'ENTITY INFORMATION');
  fieldPair(doc, 'Company Name', ws.company_name ?? '—');
  fieldPair(doc, 'License Number', ws.license_number ?? '—');
  fieldPair(doc, 'Address', [ws.address, ws.city, ws.state, ws.zip].filter(Boolean).join(', '));
  fieldPair(doc, 'Phone', ws.phone ?? '—');
  fieldPair(doc, 'Email', ws.email ?? '—');
  fieldPair(doc, 'Regulatory Body', regulatoryBody);
  fieldPair(doc, 'Active Officers', String(officers.length));
  fieldPair(doc, 'Armed Officers', String(officers.filter(o => o.is_armed).length));
  fieldPair(doc, 'UoF Incidents (12 mo)', String(incidents.length));
  fieldPair(doc, 'Armed Shift Logs (12 mo)', String(shifts.length));

  if (expiredOfficers.length > 0) {
    doc.y += 6;
    doc.rect(PAGE.ML, doc.y, PAGE.CW, 24).fill(PDF.dangerLight);
    doc.fontSize(9).fillColor(PDF.danger).font('Helvetica-Bold')
      .text(`⚠ AUDIT ALERT: ${expiredOfficers.length} armed officer(s) with expired/missing licenses`, PAGE.ML + 8, doc.y + 7, { width: PAGE.CW - 16 });
    doc.font('Helvetica');
    doc.y += 28;
  }

  // Table of contents
  doc.addPage();
  renderPdfHeader(doc, {
    title: 'TABLE OF CONTENTS', subtitle: 'Exhibit Index',
    workspaceName: ws.company_name ?? 'Security Company', tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `Packet ID: ${docId}`, generatedLabel: `Generated: ${generatedAt}`,
  });
  sectionBar(doc, 'CONTENTS');
  [
    ['Exhibit A', 'Active Guard Roster & License Status'],
    ['Exhibit B', 'Use of Force & Firearm Discharge Reports'],
    ['Exhibit C', 'Armed Post Shift Logs — Proof of Presence'],
  ].forEach(([ex, title]) => zebraRow(doc, ex, title));

  // ── EXHIBIT A — Roster ────────────────────────────────────────────────────
  doc.addPage();
  renderPdfHeader(doc, {
    title: 'EXHIBIT A — ACTIVE ROSTER & LICENSE STATUS',
    subtitle: `${officers.length} Active Officers · ${regulatoryBody}`,
    workspaceName: ws.company_name ?? 'Security Company', tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `Packet: ${docId}`, generatedLabel: generatedAt,
  });

  // Column headers
  const colA = [PAGE.ML, 160, 300, 400, 480];
  const headerY = PAGE.MT;
  doc.fontSize(8).fillColor(PDF.white).font('Helvetica-Bold');
  doc.rect(PAGE.ML, headerY - 2, PAGE.CW, 14).fill(PDF.navy);
  ['Officer Name', 'Guard Card #', 'Classification', 'Expiry', 'Status'].forEach((h, i) => {
    doc.fillColor(PDF.white).text(h, colA[i] + 2, headerY + 1);
  });
  doc.font('Helvetica');

  let rowY = headerY + 16;
  officers.forEach((o, idx) => {
    if (rowY > 700) { doc.addPage(); rowY = PAGE.MT; }
    if (idx % 2 === 0) doc.rect(PAGE.ML, rowY - 2, PAGE.CW, 12).fill(PDF.offWhite);
    const expiry = o.guard_card_expiry_date ? new Date(o.guard_card_expiry_date).toLocaleDateString() : '—';
    const status = o.guard_card_status === 'active' || o.armed_license_verified ? 'ACTIVE'
      : o.guard_card_status === 'expired_hard_block' ? 'EXPIRED' : 'UNVERIFIED';
    const statusColor = status === 'ACTIVE' ? PDF.success : PDF.danger;
    const typeName = o.license_type
      ? o.license_type.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())
      : '—';
    doc.fontSize(8).fillColor(PDF.dark);
    doc.text(`${o.last_name}, ${o.first_name}`, colA[0] + 2, rowY);
    doc.text(o.guard_card_number ?? 'MISSING', colA[1] + 2, rowY);
    doc.text(typeName, colA[2] + 2, rowY, { width: 90 });
    doc.text(expiry, colA[3] + 2, rowY);
    doc.fillColor(statusColor).text(status, colA[4] + 2, rowY);
    doc.fillColor(PDF.dark);
    rowY += 13;
  });

  // ── EXHIBIT B — Use of Force ───────────────────────────────────────────────
  doc.addPage();
  renderPdfHeader(doc, {
    title: 'EXHIBIT B — USE OF FORCE REPORTS',
    subtitle: `${incidents.length} Incident(s) · 12-Month Period`,
    workspaceName: ws.company_name ?? 'Security Company', tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `Packet: ${docId}`, generatedLabel: generatedAt,
  });

  if (incidents.length === 0) {
    doc.fontSize(11).fillColor(PDF.success).font('Helvetica-Bold')
      .text('✓ No Use of Force incidents recorded in the past 12 months.', PAGE.ML, PAGE.MT + 20, { width: PAGE.CW });
    doc.font('Helvetica');
  } else {
    let incY = PAGE.MT;
    incidents.forEach((inc, idx) => {
      if (incY > 680) { doc.addPage(); incY = PAGE.MT; }
      doc.fontSize(9).fillColor(PDF.navyMid).font('Helvetica-Bold')
        .text(`${idx + 1}. ${inc.incident_number ?? 'No #'} — ${inc.title}`, PAGE.ML, incY, { width: PAGE.CW });
      incY = doc.y + 2;
      doc.font('Helvetica').fillColor(PDF.gray).fontSize(8)
        .text(
          `Date: ${new Date(inc.created_at).toLocaleDateString()}  |  Type: ${inc.incident_type.replace(/_/g,' ').toUpperCase()}  |  Severity: ${inc.severity.toUpperCase()}  |  Status: ${inc.status.replace(/_/g,' ').toUpperCase()}`,
          PAGE.ML + 8, incY, { width: PAGE.CW }
        );
      incY = doc.y + 2;
      if (inc.polished_description) {
        doc.fillColor(PDF.dark).fontSize(8)
          .text(inc.polished_description.slice(0, 300) + (inc.polished_description.length > 300 ? '…' : ''),
            PAGE.ML + 8, incY, { width: PAGE.CW - 8 });
        incY = doc.y + 4;
      }
      doc.moveTo(PAGE.ML, incY).lineTo(PAGE.ML + PAGE.CW, incY).stroke(PDF.grayLight);
      incY += 6;
    });
  }

  // ── EXHIBIT C — Shift Logs ────────────────────────────────────────────────
  doc.addPage();
  renderPdfHeader(doc, {
    title: 'EXHIBIT C — ARMED POST SHIFT LOGS',
    subtitle: `${shifts.length} Shift(s) · 12-Month Period`,
    workspaceName: ws.company_name ?? 'Security Company', tenantLogoBuffer: logoBuffer ?? undefined,
    refLabel: `Packet: ${docId}`, generatedLabel: generatedAt,
  });

  const colC = [PAGE.ML, 160, 290, 400, 490];
  doc.rect(PAGE.ML, PAGE.MT - 2, PAGE.CW, 14).fill(PDF.navy);
  doc.fontSize(8).fillColor(PDF.white).font('Helvetica-Bold');
  ['Officer', 'Guard Card #', 'Site', 'Start', 'Status'].forEach((h, i) => {
    doc.text(h, colC[i] + 2, PAGE.MT + 1);
  });
  doc.font('Helvetica');
  let shiftRowY = PAGE.MT + 16;
  shifts.forEach((s, idx) => {
    if (shiftRowY > 720) { doc.addPage(); shiftRowY = PAGE.MT; }
    if (idx % 2 === 0) doc.rect(PAGE.ML, shiftRowY - 2, PAGE.CW, 12).fill(PDF.offWhite);
    doc.fontSize(7.5).fillColor(PDF.dark);
    doc.text(s.officer_name ?? '—', colC[0] + 2, shiftRowY, { width: 100 });
    doc.text(s.guard_card_number ?? 'MISSING', colC[1] + 2, shiftRowY, { width: 90 });
    doc.text((s.site_name ?? '—').slice(0, 28), colC[2] + 2, shiftRowY, { width: 110 });
    doc.text(s.start_time ? new Date(s.start_time).toLocaleDateString() : '—', colC[3] + 2, shiftRowY);
    doc.text((s.status ?? '—').toUpperCase(), colC[4] + 2, shiftRowY);
    shiftRowY += 13;
  });

  renderPdfFooter(doc, {
    docId, docType: 'DPS AUDIT PACKET', workspaceName: ws.company_name ?? 'Security Company',
  });

  await new Promise<void>(resolve => { doc.end(); doc.on('end', resolve); });
  const buffer = Buffer.concat(chunks);
  const pageCount = (doc as Record<string, unknown>)._pageBuffer
    ? ((doc as Record<string, unknown>)._pageBuffer as unknown[]).length
    : 1;

  await logGeneratedDoc({
    workspaceId, documentType: 'dps_audit_packet', docId,
    fileSizeBytes: buffer.length, pageCount,
    generatedBy, generatedByName,
  });

  log.info(`[PDFEngine] DPS Audit Packet generated: ${docId}, ${pageCount} pages, ${Math.round(buffer.length / 1024)}KB`);
  return { buffer, docId, filename: `DPS-Audit-Packet-${docId}.pdf`, pageCount };
}
